import type { Metadata } from "next";
import { montserrat } from '@/utils/fonts';
import Navbar from "@/components/navbar/navbar";
import Footer from '@/components/footer/footer';

import "./globals.css";

 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const navbarLinks = [
  {name: "Home", url: "#hero"},
  {name: "About", url: "#about"},
  {name: "Education", url: "#education"},
  {name: "Skills", url: "#skills"},
  {name: "Services", url: "#services"},
];


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.className} antialiased`}
      >
        <Navbar links={navbarLinks} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
